### ISSUE TITLE
Remove TPC development branch after merging?

### ISSUE THREAD

**Issue by blackcathj** [sPHENIX-Collaboration/coresoftware#39] opened 2015-09-11 16:38 UTC
Thanks @mccumbermike  and @alandion for merging the TPC branch into master in pull request #35 .  Now TPC branch do not carry any new commits. Now I am writing to start a discussion on relocating the TPC development branch:

Shall we remove it from the sPHENIX-Collaboration/coresoftware repository? The goal is to keep the branch structure in sPHENIX main repositories clean, and only carry master, production and few to-be-merged evaluation branches for larger circle of collaborator to test. Currently there is a to-be-merged evaluation branch CaloTower from @nfeege , which we should merge after the pre-CDR simulation runs. 

To keep the TPC development on GitHub, we have a few options:

1. For one developer to contribute commits and for TPC experts to use: we can make a fork repository in personal area, add TPC development branch on it, and update/publish it for other TPC experts to use. 
Example is my SPACAL development branch:
https://github.com/blackcathj/coresoftware/tree/SPACALTower-NewEval-Tower
which was merged into sPHENIX master after the development and test was finished through pull request #29 
PS: multiple developers can also exchange contributions through pull request between forks. 

2. For shared development among multiple developers. 
An easy way to do so on GitHub would be making an organization of tracking group experts, fork coresoftware in that organization, so all tracking expert can commit. And when the software is ready for wider use, we can merge it into sPHENIX through a pull request. Much like personal fork too. 

3. If there is good reason to keep TPC branch on sPHENIX repository, I would like to learn too. But in the end, we would like to avoid many test/dev branches on sPHENIX repository, which would become confusing to non-expert to follow their purpose and status.

**Comment by alandion** [comment] 2015-09-15 20:43
I think option 1 is the easiest way to go for now.  I will remove the TPC branch, and then create a testing TPC branch with the intention that merges into master will be done as soon as others in the TPC group have tested them

**Comment by mccumbermike** [comment] 2015-09-15 22:59
I think so too, I find working with additional remote repositories easy enough. We can always branch again in the future if we are wrong.

**Comment by mccumbermike** [comment] 2015-10-10 04:55
I solved the crash that the one commit left on this branch was intended to circumvent some time ago. I'm going to delete the branch (it can be recovered if needed) and close this ticket. Reopen if I'm mistaken.

**Closed by mccumbermike** 2015-10-10 04:55 UTC
Labels: help wanted, question
